export const colleges = [
  {
    id: 1,
    name: 'LNCT Lakshmi Narain College of Technology ',
    logo: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748889083/link-generator/ghvgi1rfdugpj4ul3vzw.webp',
    image:
      'https://res.cloudinary.com/doxmvuss9/image/upload/v1748889457/link-generator/zudwsnowgwoea2ky9fkb.webp',
    address: 'Kalchuri Nagar, Raisen Road, Bhopal',
    website: 'https://lnct.ac.in',
  },
  {
    id: 2,
    name: 'JNCT Professional University',
    logo: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748889035/link-generator/yititzqywmkuf0y9irbj.webp',
    image:
      'https://res.cloudinary.com/doxmvuss9/image/upload/v1748889416/link-generator/bpichj2vsupaohdt4tum.webp',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://jnctpu.edu.in',
  },
  {
    id: 3,
    name: 'Indore LN Medical College',
    logo: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748890248/link-generator/zezkbne95lbso8a1groy.png',
    image:
      'https://res.cloudinary.com/doxmvuss9/image/upload/v1748890249/link-generator/tsxlhjl7fbbnyz50vvcy.jpg',
    address: 'Indore, Madhya Pradesh',
    website: 'https://indorelnmc.com',
  },
  {
    id: 4,
    name: 'LNCP Bhopal',
    logo: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748890247/link-generator/znesyztnlzpdeub3nsdu.png',
    image:
      'https://res.cloudinary.com/doxmvuss9/image/upload/v1748890244/link-generator/tk31qlcflxqhycdv6ccv.jpg',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lncpbhopal.in',
  },
  {
    id: 5,
    name: 'LNCT Bhopal',
    logo: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748890246/link-generator/ukhwhdyv9ly2yzlppgjc.png',
    image:
      'https://res.cloudinary.com/doxmvuss9/image/upload/v1748890245/link-generator/sny0xmbylgucqrxiagac.jpg',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lnctbhopal.in',
  },
  {
    id: 6,
    name: 'LNCT Engineering College',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lncte.in',
  },
  {
    id: 7,
    name: 'LNCT Bhopal Indore Campus',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Indore, Madhya Pradesh',
    website: 'https://lnctbplindorecampus.in',
  },
  {
    id: 8,
    name: 'CLC Homeopathy College',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://clchomeopathy.in',
  },
  {
    id: 9,
    name: 'LNCT University',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lnctu.ac.in',
  },
  {
    id: 10,
    name: 'JNCT Bhopal',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://jnctbhopal.ac.in',
  },
  {
    id: 11,
    name: 'LNCT Vidhyapeeth University',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lnctvu.ac.in',
  },
  {
    id: 12,
    name: 'Jayant Jaggery College',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://jayantjaggery.com',
  },
  {
    id: 13,
    name: 'Indore LN Medical College',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Indore, Madhya Pradesh',
    website: 'https://indorelnmc.in',
  },
  {
    id: 14,
    name: 'CEC Bilaspur',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bilaspur, Chhattisgarh',
    website: 'https://cecbilaspur.ac.in',
  },
  {
    id: 15,
    name: 'LNCT Jabalpur',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Jabalpur, Madhya Pradesh',
    website: 'https://lnctuj.com',
  },
  {
    id: 16,
    name: 'LNCT & Science',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lncts.in',
  },
  {
    id: 17,
    name: 'LNCT MCA College',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lnctmca.in',
  },
  {
    id: 18,
    name: 'IPS Bilaspur',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bilaspur, Chhattisgarh',
    website: 'https://ipsbilaspur.com',
  },
  {
    id: 19,
    name: 'LN Ayurved College',
    logo: '/placeholder.svg?height=60&width=60',
    image: '/placeholder.svg?height=300&width=400',
    address: 'Bhopal, Madhya Pradesh',
    website: 'https://lnayurvedcollege.com',
  },
]
