// constants/eminentAlllumni.js
export const eminentAlumni = {
  civilServices: [
    {
      name: 'Mr. Anis Rahman',
      position: 'Director',
      company: 'Ministry of Communication (Govt. of India)',
      batch: '2001',
      department: 'EC',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749899677/link-generator/ziuugz9iyqsezk27oywh.jpg',
      achievements: [
        'Indian Engineering Services (IES)',
        'Director at Ministry of Communication, Government of India',
      ],
    },
    {
      name: 'Mr. Avadh Kishor Pawar',
      position: 'Dy. Director',
      company: 'Enforcement Directorate, Delhi',
      batch: '2009',
      department: 'Civil Engineering',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749899638/link-generator/nrbyvpkv8zvyd1ofk0er.jpg',
      achievements: [
        'Indian Revenue Service (IRS)',
        'Deputy Director at Enforcement Directorate, Delhi',
      ],
    },
    {
      name: 'Mr. Karan Singh Saini',
      position: 'Asst. Commissioner',
      company: 'Ministry of Water Resources',
      batch: '2014',
      department: 'Civil Engineering',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749902186/link-generator/nmib7u9kgywpal8y8rnv.jpg',
      achievements: [
        'Indian Engineering Services (IES)',
        'Assistant Commissioner at Ministry of Water Resources',
      ],
    },
    {
      name: 'Ms. Srushti Jayant Deshmukh',
      position: 'IAS Officer',
      company: 'Indian Administrative Service',
      batch: '2018',
      department: 'Chemical Engineering',
      image: '/alumni/eminent/srushti-deshmukh.jpg',
      achievements: [
        'Indian Administrative Service (IAS)',
        'Chemical Engineering Graduate',
      ],
    },
    {
      name: 'Ms. Ayushi Jain',
      position: 'S.D.O. (Sub Divisional Officer)',
      company: 'Nazira, Assam',
      batch: '2014',
      department: 'CSE',
      image: '/alumni/eminent/ayushi-jain.jpg',
      achievements: [
        'Indian Administrative Service (IAS)',
        'Sub Divisional Officer at Nazira, Assam',
      ],
    },
    {
      name: 'Mr. Ankit Jain',
      position: 'SP (Superintendent of Police)',
      company: 'Zone-1 Bhopal M.P.',
      batch: '2014',
      department: 'CSE',
      image: '/alumni/eminent/ayushi-jain.jpg',
      achievements: [
        'Indian Police Service (IPS)',
        'Additonal SP at Zone-1 Bhopal M.P.',
      ],
    },
    {
      name: 'Ms. Pratibha Sharma',
      position: 'DSP (Deputy Superintendent of Police)',
      company: 'Bhopal Central Zone M.P.',
      batch: '2016',
      department: 'EC',
      image: '/alumni/eminent/ayushi-jain.jpg',
      achievements: [
        'Indian Police Service (IPS)',
        'DSP Central Zone Bhopal M.P.',
      ],
    },
    {
      name: 'Mr. Aditi Bhawsar',
      position: 'IPS Officer',
      company: 'SDOP Raisen Bhopal M.P.',
      batch: '2014',
      department: 'CSE',
      image: '/alumni/eminent/ayushi-jain.jpg',
      achievements: [
        'Indian Police Service (IPS)',
        'Additonal SP at Zone-1 Bhopal M.P.',
      ],
    },
  ],
  publicSector: [
    {
      name: 'Mr. Salman Khan',
      position: 'Assistant Engineer',
      company: 'Uttar Pradesh Irrigation and Water Resources Department',
      batch: '2013',
      department: 'Civil Engineering',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749901976/link-generator/zcuv3fc6fm558yp5qqy0.jpg',
      achievements: ['Assistant Engineer at UP Irrigation Department'],
    },
    {
      name: 'Mr. Kundan Kumar',
      position: 'Assistant Engineer',
      company: 'NBPDCL-Bihar',
      batch: '2013',
      department: 'Civil Engineering',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749902298/link-generator/fmsxpkcylqh8jxw3bmmm.jpg',
      achievements: ['Assistant Engineer at NBPDCL-Bihar'],
    },
    {
      name: 'Mr. Sunil Sharma',
      position: 'Assistant Engineer',
      company: 'Ministary of Housing  and Urban Affairs,',
      batch: '2013',
      department: 'Civil Engineering',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749904222/link-generator/u3moell6elea2kcxycpg.png',
      achievements: ['Assistant Engineer Nagpur', ''],
    },
    {
      name: 'Ms. Pooja Verma',
      position: 'Assistant Engineer',
      company: 'MPWRD, NVDA',
      batch: '2017',
      department: 'Civil Engineering',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749904222/link-generator/u3moell6elea2kcxycpg.png',
      achievements: ['Assistant Engineer NVDA', ''],
    },
  ],
  nri: [
    {
      name: 'Mr. Kamlesh Gehani',
      position: 'Sr. Business Analyst',
      company: 'Devita Inc. USA',
      batch: '1998',
      department: 'CSE',
      image: '/alumni/eminent/kamlesh-gehani.jpg',
      achievements: ['Senior Business Analyst at Devita Inc. USA'],
    },
    {
      name: 'Mr. Siddhartha Saran',
      position: 'Director IT',
      company: 'Gap Inc. USA',
      batch: '1998',
      department: 'CSE',
      image: '/alumni/eminent/siddhartha-saran.jpg',
      achievements: ['Director IT at Gap Inc. USA'],
    },
    {
      name: 'Mr. Faizal Khan',
      position: 'US Army',
      company: ' Department of Defense, USA',
      batch: '2003',
      department: 'EE',
      image: '/alumni/eminent/siddhartha-saran.jpg',
      achievements: ['In US Army'],
    },
    {
      name: 'Mr. Shiddhartha Saran',
      position: 'Director IT',
      company: ' Gap Inc. USA',
      batch: '1998',
      department: 'CSE',
      image: '/alumni/eminent/siddhartha-saran.jpg',
      achievements: [
        'Director of IT Department',
        'Working to make future better',
      ],
    },
  ],
  corporate: [
    {
      name: 'Dr. Nitin Jain',
      position: 'Image Quality Architect',
      company: 'GE Healthcare Bangalore',
      batch: '2001',
      department: 'EE',
      image: '/alumni/eminent/nitin-jain.jpg',
      achievements: [
        'Image Quality Architect at GE Healthcare',
        'Expert in Medical Imaging Technology',
      ],
    },
    {
      name: 'Mr. Kumar Aman',
      position: 'Executive Production & Research Coordinator',
      company: 'Gujarat Credo Alumina Pvt. Ltd',
      batch: '2019',
      department: 'CM',
      image: '/alumni/eminent/kumar-aman.jpg',
      achievements: [
        'Executive Production & Research Coordinator',
        'Leading production and research initiatives',
      ],
    },
    {
      name: 'Mr. Shubhendra Upadhyay ',
      position: 'CEO',
      company: 'Conivivial Groups of Hotals',
      batch: '2018',
      department: 'Management ',
      image: '/alumni/eminent/kumar-aman.jpg',
      achievements: ['CEO'],
    },
    {
      name: 'Ms. Khushboo ',
      position: 'Software Associate',
      company: 'Hoerbiger, Pune',
      batch: '2018',
      department: 'Software Management',
      image: '/alumni/eminent/kumar-aman.jpg',
      achievements: ['Softwar Associate', 'Working towards bright future'],
    },
  ],
  scientists: [
    {
      name: 'Mr. Rajendra Kirar',
      position: 'Scientist',
      company: 'DEFENCE RESEARCH AND DEVELOPMENT ORGANIZATION, NAGPUR',
      batch: '2011',
      department: 'EC',
      image: '/alumni/eminent/rajendra-kirar.jpg',
      achievements: [
        'Scientist at DRDO Nagpur',
        'Contributing to defense research',
      ],
    },
    {
      name: 'Mr. Praveen Kumar',
      position: 'Scientist',
      company: 'INDIAN SPACE RESEARCH ORGANIZATION, AHMEDABAD',
      batch: '2015',
      department: 'EC',
      image: '/alumni/eminent/praveen-kumar.jpg',
      achievements: [
        'Scientist at ISRO Ahmedabad',
        'Contributing to space research',
      ],
    },
    {
      name: 'Ms. Shweta Kirkire',
      position: 'Scientist',
      company: 'INDIAN SPACE RESEARCH ORGANIZATION (ISRO)',
      batch: '2005',
      department: 'EC',
      image: '/alumni/eminent/praveen-kumar.jpg',
      achievements: [''],
    },
    {
      name: 'Mr. Sachin Malviya',
      position: 'Scientist',
      company: 'INDIAN SPACE RESEARCH ORGANIZATION, (ISRO) ',
      batch: '2008',
      department: 'EC',
      image: '/alumni/eminent/praveen-kumar.jpg',
      achievements: ['Scientist at ISRO ', 'Contributing to space research'],
    },
  ],
  defense: [
    {
      name: 'Major Kanishka Sakwar',
      position: 'Pilot',
      company: 'Indian Army',
      batch: '2016',
      department: 'Civil Engineering',
      image: '/alumni/eminent/kanishka-sakwar.jpg',
      achievements: ['Pilot in Indian Army', 'Major rank officer'],
    },
    {
      name: 'Mr. Manish Rajput',
      position: 'Lieutenant',
      company: 'Indian Navy',
      batch: '2013',
      department: 'EX',
      image: '/alumni/eminent/manish-rajput.jpg',
      achievements: [
        'Lieutenant in Indian Navy',
        'Serving in the defense forces',
      ],
    },
    {
      name: 'Mr. Mayank S Pandey',
      position: 'Captain',
      company: 'Indian Army',
      batch: '2016',
      department: 'ME',
      image: '/alumni/eminent/manish-rajput.jpg',
      achievements: ['Captain in Indian Navy', 'Serving in the defense forces'],
    },
    {
      name: 'Major Kanishka Sakwar',
      position: 'Pilot',
      company: 'Indian Army',
      batch: '2016',
      department: 'Civil',
      image: '/alumni/eminent/manish-rajput.jpg',
      achievements: ['Captain in Indian Navy', 'Serving in the defense forces'],
    },
  ],
  professors: [
    {
      name: 'Dr. Ankit Jain',
      position: 'Professor',
      company: 'NIT KURUKSHETRA',
      batch: '2009',
      department: 'CSE',
      image:
        'https://res.cloudinary.com/doxmvuss9/image/upload/v1749902502/link-generator/yrhazhghpudmpt8hq1iw.jpg',
      achievements: [
        'Professor at NIT Kurukshetra',
        'Contributing to academic excellence',
      ],
    },
    {
      name: 'Dr. Manish Pandey',
      position: 'Professor',
      company: 'MANIT BHOPAL',
      batch: '2001',
      department: 'CSE',
      image: '/alumni/eminent/manish-pandey.jpg',
      achievements: [
        'Professor at MANIT Bhopal',
        'Leading academic initiatives',
      ],
    },
    {
      name: 'Prof. Akhilesh Soni',
      position: 'Professor',
      company: 'MANIT BHOPAL',
      batch: '2002',
      department: 'ME',
      image: '/alumni/eminent/manish-pandey.jpg',
      achievements: [
        'Professor at MANIT Bhopal',
        'Leading academic initiatives',
      ],
    },
    {
      name: 'Dr. Praveen Kaushik',
      position: 'Professor',
      company: 'MANIT BHOPAL',
      batch: '2001',
      department: 'CSE',
      image: '/alumni/eminent/manish-pandey.jpg',
      achievements: [
        'Professor at MANIT Bhopal',
        'Leading academic initiatives',
      ],
    },
  ],
}
