const firmsData = {
  firms: [
    {
      name: 'Ananjay Private Limited',
      description: '',
      link: 'https://ananjay.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Dabra Alcobrew Private Limited',
      description: '',
      link: 'https://dabraalcobrew.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Rishiraj College of Dental Sciences and Research Centre',
      description: '',
      link: 'https://lnctrishiraj.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Ananjay Pharmaceuticals Private Limited',
      description: '',
      link: 'https://ananjaypharma.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Vitamax',
      description: '',
      link: 'https://vitamax.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Parvati Sweetners and Power Limited',
      description: '',
      link: 'https://parvatisweetners.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Kalchuri Contractors Ltd.',
      description: '',
      link: 'https://kalchuricontractors.ltd',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
  ],

}

export default firmsData;