// Gallery data structure
export const videos = [
  {
    id: 1,
    url: 'https://files.edgestore.dev/r7t8qow2hwrnycyu/jatin/_public/15e62424-4ade-40bb-ad16-a41d30185137.mp4',
  },
  {
    id: 2,
    title: 'Sample Video 1',
    description: 'This is a sample video description',
    tags: ['nature', 'landscape'],
    hashtags: ['#nature', '#beautiful', '#landscape'],
    url: 'https://files.edgestore.dev/r7t8qow2hwrnycyu/jatin/_public/c192f638-7a0c-467a-86b6-b4b5f0c5ba90.mp4',
  },
  {
    id: 3,
    title: 'Sample Video 1',
    description: 'This is a sample video description',
    tags: ['nature', 'landscape'],
    hashtags: ['#nature', '#beautiful', '#landscape'],
    url: 'https://files.edgestore.dev/r7t8qow2hwrnycyu/jatin/_public/c192f638-7a0c-467a-86b6-b4b5f0c5ba90.mp4',
  },
]

export const shots = [
  {
    id: 1,
    title: 'Beautiful Landscape',
    description: 'A stunning landscape shot',
    tags: ['landscape', 'nature'],
    hashtags: ['#landscape', '#nature', '#photography'],
    url: 'https://files.edgestore.dev/r7t8qow2hwrnycyu/jatin/_public/c9c9d529-616d-4ee1-bb14-2a270bb9b26a.mp4',
  },
  {
    id: 2,
    title: 'Beautiful Landscape',
    description: 'A stunning landscape shot',
    tags: ['landscape', 'nature'],
    hashtags: ['#landscape', '#nature', '#photography'],
    url: 'https://files.edgestore.dev/r7t8qow2hwrnycyu/jatin/_public/a2946749-be17-4097-a790-9698badb4ae9.mp4',
  },
]

export const photos = [
  {
    id: 5,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748937650/link-generator/t7zeh3n1wne8tafklzkh.jpg',
  },
  {
    id: 6,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748937651/link-generator/x3guvasldppdbpmsrapu.jpg',
  },
  {
    id: 7,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748937652/link-generator/ojvry5jtmtgjncttofl7.jpg',
  },
  {
    id: 8,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748937653/link-generator/jfyysdmwcblyjzwj8qfq.jpg',
  },

  {
    id: 1,
    title: 'Sunset Beach',
    description: 'Beautiful sunset at the beach',
    tags: ['sunset', 'beach', 'ocean'],
    hashtags: ['#sunset', '#beach', '#ocean', '#golden'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935515/link-generator/lzuuoc38uszmea1gc8wy.jpg',
  },
  {
    id: 2,
    title: 'Mountain Peak',
    description: 'Snow-capped mountain peak',
    tags: ['mountain', 'snow', 'peak'],
    hashtags: ['#mountain', '#snow', '#adventure'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935516/link-generator/uoznnq12a8ak7qe1kiz1.jpg',
  },
  {
    id: 3,
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935517/link-generator/ztzehafinbkuejh5pgqm.jpg',
  },
  {
    id: 4,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935773/link-generator/kgpid4muemc2ghwrhhss.jpg',
  },
  {
    id: 9,
    title: 'Sunset Beach',
    description: 'Beautiful sunset at the beach',
    tags: ['sunset', 'beach', 'ocean'],
    hashtags: ['#sunset', '#beach', '#ocean', '#golden'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935515/link-generator/lzuuoc38uszmea1gc8wy.jpg',
  },
  {
    id: 10,
    title: 'Mountain Peak',
    description: 'Snow-capped mountain peak',
    tags: ['mountain', 'snow', 'peak'],
    hashtags: ['#mountain', '#snow', '#adventure'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935516/link-generator/uoznnq12a8ak7qe1kiz1.jpg',
  },
  {
    id: 11,
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935517/link-generator/ztzehafinbkuejh5pgqm.jpg',
  },
  {
    id: 12,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: 'https://res.cloudinary.com/doxmvuss9/image/upload/v1748935773/link-generator/kgpid4muemc2ghwrhhss.jpg',
  },
  {
    id: 13,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: '/placeholder.svg?height=600&width=400',
  },
  {
    id: 14,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: '/placeholder.svg?height=600&width=400',
  },
  {
    id: 15,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: '/placeholder.svg?height=600&width=400',
  },
  {
    id: 16,
    title: 'Forest Path',
    description: 'Peaceful forest walking path',
    tags: ['forest', 'nature', 'path'],
    hashtags: ['#forest', '#nature', '#peaceful'],
    url: '/placeholder.svg?height=600&width=400',
  },
]
