const siteData = {
  colleges: [
    {
      name: 'LNCT',
      description: '',
      link: 'https://lnct.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'JNCT Professional University',
      description: '',
      link: 'https://jnctpu.edu.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Indore LN Medical College',
      description: '',
      link: 'https://indorelnmc.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'LNCP Bhopal',
      description: '',
      link: 'https://lncpbhopal.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
    {
      name: 'LNCT Bhopal',
      description: '',
      link: 'https://lnctbhopal.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
    {
      name: 'LNCT Engineering College',
      description: '',
      link: 'https://lncte.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT Bhopal Indore Campus',
      description: '',
      link: 'https://lnctbplindorecampus.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'CLC Homeopathy College',
      description: '',
      link: 'https://clchomeopathy.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT University',
      description: '',
      link: 'https://lnctu.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'JNCT Bhopal',
      description: '',
      link: 'https://jnctbhopal.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
    {
      name: 'LNCT Vidhyapeeth University',
      description: '',
      link: 'https://lnctvu.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'Jayant Jaggery College',
      description: '',
      link: 'https://jayantjaggery.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Indore LN Medical College (alt)',
      description: '',
      link: 'https://indorelnmc.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'CEC Bilaspur',
      description: '',
      link: 'https://cecbilaspur.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bilaspur',
    },
    {
      name: 'LNCT Jabalpur',
      description: '',
      link: 'https://lnctuj.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Jabalpur',
    },
    {
      name: 'LNCT & Science',
      description: '',
      link: 'https://lncts.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT MCA College',
      description: '',
      link: 'https://lnctmca.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'IPS Bilaspur',
      description: '',
      link: 'https://ipsbilaspur.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bilaspur',
    },
    {
      name: 'LN Ayurved College',
      description: '',
      link: 'https://lnayurvedcollege.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
  ],

  school: [
    {
      name: 'LNCT World School',
      description: '',
      link: 'https://lnctworldschools.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
  ],

  firms: [
    {
      name: 'Ananjay Private Limited',
      description: '',
      link: 'https://ananjay.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Dabra Alcobrew Private Limited',
      description: '',
      link: 'https://dabraalcobrew.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Rishiraj College of Dental Sciences and Research Centre',
      description: '',
      link: 'https://lnctrishiraj.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Ananjay Pharmaceuticals Private Limited',
      description: '',
      link: 'https://ananjaypharma.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Vitamax',
      description: '',
      link: 'https://vitamax.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Parvati Sweetners and Power Limited',
      description: '',
      link: 'https://parvatisweetners.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Kalchuri Contractors Ltd.',
      description: '',
      link: 'https://kalchuricontractors.ltd',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
  ],

  errorPages: [
    {
      name: 'LNCTP School (Error)',
      description: '',
      link: 'https://lncps.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCTS Op Indore (Error)',
      description: '',
      link: 'https://lnctsopindore.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'JNCN (Error)',
      description: '',
      link: 'https://jncn.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT Guru (Error)',
      description: '',
      link: 'https://lnctguru.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
  ],
}

export default siteData
