const siteData = {
  colleges: [
    {
      name: 'Lakshmi Narain College of Technology (LNCT)',
      description:
        'Lakshmi Narain College of Technology (LNCT), established in 1994, is a premier private engineering and management institute located in Bhopal, Madhya Pradesh. Affiliated with RGPV and approved by AICTE, LNCT offers a range of undergraduate and postgraduate programs in engineering, management, pharmacy, and computer applications. The college is known for its state-of-the-art infrastructure, experienced faculty, and strong placement records.',
      link: 'https://lnct.ac.in',
      logo: 'https://lnct.ac.in/wp-content/uploads/2021/04/lnct-logo.png',
      photos: [
        {
          name: 'Main Campus Building',
          tag: 'Campus',
          description: 'The main academic building of LNCT Bhopal.',
          url: 'https://lnct.ac.in/wp-content/uploads/2021/04/lnct-campus.jpg',
        },
        {
          name: 'Digital Library',
          tag: 'Library',
          description:
            'State-of-the-art digital library accessible to all students.',
          url: 'https://lnct.ac.in/wp-content/uploads/2021/04/lnct-library.jpg',
        },
        {
          name: 'Hostel Facilities',
          tag: 'Hostel',
          description:
            'Comfortable and secure hostel accommodations for students.',
          url: 'https://lnct.ac.in/wp-content/uploads/2021/04/lnct-hostel.jpg',
        },
      ],
      eventsPhotos: [
        {
          name: 'LNUniverse 2025',
          tag: 'Cultural Fest',
          description:
            'Annual cultural fest featuring music, dance, and drama performances.',
          url: 'https://lnct.ac.in/wp-content/uploads/2025/05/lnuniverse-2025.jpg',
        },
        {
          name: 'IEEE Orientation Program',
          tag: 'Technical Event',
          description:
            'Orientation program for newly joined IEEE student members.',
          url: 'https://lnct.ac.in/wp-content/uploads/2025/04/ieee-orientation.jpg',
        },
        {
          name: 'Lake-city Hackathon Winners',
          tag: 'Hackathon',
          description: 'LNCT students winning the Lake-city Hackathon.',
          url: 'https://lnct.ac.in/wp-content/uploads/2025/04/hackathon-winners.jpg',
        },
      ],
      address:
        'Kalchuri Nagar, (P.O. Kolua), Raisen Road, Bhopal - 462022, Madhya Pradesh, India',
      number: [
        '+91-755-6185300',
        '+91-755-6185301',
        '+91-755-6185302',
        '+91-755-6185303',
        '+91-755-6185304',
        '+91-755-6185305',
        '+91-7440777111',
        '+91-7201800001',
      ],
      location: {
        latitude: 23.2335,
        longitude: 77.4977,
      },
      city: 'Bhopal',
    },
    {
      name: 'JNCT Professional University',
      description: '',
      link: 'https://jnctpu.edu.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Indore LN Medical College',
      description: '',
      link: 'https://indorelnmc.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'LNCP Bhopal',
      description: '',
      link: 'https://lncpbhopal.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
    {
      name: 'LNCT Bhopal',
      description: '',
      link: 'https://lnctbhopal.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
    {
      name: 'LNCT Engineering College',
      description: '',
      link: 'https://lncte.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT Bhopal Indore Campus',
      description: '',
      link: 'https://lnctbplindorecampus.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'CLC Homeopathy College',
      description: '',
      link: 'https://clchomeopathy.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT University',
      description: '',
      link: 'https://lnctu.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'JNCT Bhopal',
      description: '',
      link: 'https://jnctbhopal.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
    {
      name: 'LNCT Vidhyapeeth University',
      description: '',
      link: 'https://lnctvu.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'Jayant Jaggery College',
      description: '',
      link: 'https://jayantjaggery.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Indore LN Medical College (alt)',
      description: '',
      link: 'https://indorelnmc.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Indore',
    },
    {
      name: 'CEC Bilaspur',
      description: '',
      link: 'https://cecbilaspur.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bilaspur',
    },
    {
      name: 'LNCT Jabalpur',
      description: '',
      link: 'https://lnctuj.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Jabalpur',
    },
    {
      name: 'LNCT & Science',
      description: '',
      link: 'https://lncts.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT MCA College',
      description: '',
      link: 'https://lnctmca.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'IPS Bilaspur',
      description: '',
      link: 'https://ipsbilaspur.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bilaspur',
    },
    {
      name: 'LN Ayurved College',
      description: '',
      link: 'https://lnayurvedcollege.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
  ],

  school: [
    {
      name: 'LNCT World School',
      description: '',
      link: 'https://lnctworldschools.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: 'Bhopal',
    },
  ],

  firms: [
    {
      name: 'Ananjay Private Limited',
      description: '',
      link: 'https://ananjay.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Dabra Alcobrew Private Limited',
      description: '',
      link: 'https://dabraalcobrew.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Rishiraj College of Dental Sciences and Research Centre',
      description: '',
      link: 'https://lnctrishiraj.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Ananjay Pharmaceuticals Private Limited',
      description: '',
      link: 'https://ananjaypharma.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Vitamax',
      description: '',
      link: 'https://vitamax.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Parvati Sweetners and Power Limited',
      description: '',
      link: 'https://parvatisweetners.co.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'Kalchuri Contractors Ltd.',
      description: '',
      link: 'https://kalchuricontractors.ltd',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
  ],

  errorPages: [
    {
      name: 'LNCTP School (Error)',
      description: '',
      link: 'https://lncps.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCTS Op Indore (Error)',
      description: '',
      link: 'https://lnctsopindore.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'JNCN (Error)',
      description: '',
      link: 'https://jncn.ac.in',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
    {
      name: 'LNCT Guru (Error)',
      description: '',
      link: 'https://lnctguru.com',
      logo: '',
      photos: [],
      eventsPhotos: [],
      address: '',
      number: [],
      location: { latitude: null, longitude: null },
      city: '',
    },
  ],
}

export default siteData
